# Profile para desenvolvimento local
spring:
  config:
    activate:
      on-profile: [ local ]
  datasource:
    master:
      url: jdbc:postgresql://localhost:5432/scalingdb
      username: admin
      password: password123
      driver-class-name: org.postgresql.Driver
      hikari:
        pool-name: MasterPool
        maximum-pool-size: 20
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
    slave:
      url: jdbc:postgresql://localhost:5433/scalingdb
      username: admin
      password: password123
      driver-class-name: org.postgresql.Driver
      hikari:
        pool-name: SlavePool
        maximum-pool-size: 30
        minimum-idle: 10
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
        read-only: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
