spring:
  application:
    name: spring-postgres-crud-demo
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: postgresql

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    dev: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.springframework.core.env: DEBUG
    com.zaxxer.hikari: INFO
    org.springframework.boot.autoconfigure.jdbc.DataSourceProperties: DEBUG